services:
  # Service Database
  db:
    image: mysql:8.0
    container_name: go_auth_db_container
    restart: always
    environment:
      MYSQL_DATABASE: go_auth_db
      MYSQL_ROOT_PASSWORD: password_kamu
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Service Aplikasi Golang
  app:
    build: .
    container_name: go_auth_api_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - GIN_MODE=release
      - PORT=8080
      - DB_USER=root
      - DB_PASSWORD=password_kamu
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=go_auth_db
      - JWT_SECRET=SangatRahasia123!

volumes:
  db_data: